version = 1

# Analyzers you want to enable
[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  # Match your code style / config
  environment = ["nodejs", "browser"] 
  dialect = "typescript"              
  patterns = [
    "app/**/*.{js,ts,jsx,tsx}",       
    "hooks/**/*.{js,ts,jsx,tsx}",    
    "middleware.ts",                   
    "next.config.ts",                 
    "!**/*.test.{js,ts,jsx,tsx}",    
    "!**/*.spec.{js,ts,jsx,tsx}",    
    "!cypress/**/*",                   
    "!tests/**/*",                     
    "!coverage/**/*",                 
    "!.next/**/*"                     
  ]

[[analyzers]]
name = "test-coverage"
enabled = true

  [analyzers.meta]
  coverage_threshold = 80

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "eslint"
enabled = true
