version: 2.1

# Define reusable commands
commands:
  install_dependencies:
    description: 'Install project dependencies with caching'
    steps:
      - restore_cache:
          keys:
            - v5-e2e-{{ checksum "package-lock.json" }}-{{ checksum "lambdatest-config.json" }}
            - v5-e2e-{{ checksum "package-lock.json" }}
            - v5-e2e-
      - run:
          name: 'Install npm dependencies'
          command: |
            export HUSKY=0
            echo "Node version: $(node --version)"
            echo "npm version: $(npm --version)"

            if [ -f "package-lock.json" ]; then
              npm ci --include=dev --no-audit
            else
              npm install --include=dev --no-audit
            fi
            echo "Dependencies installed successfully"
      - load_env_file
      - save_cache:
          key: v5-e2e-{{ checksum "package-lock.json" }}-{{ checksum "lambdatest-config.json" }}
          paths:
            - ~/.npm
            - node_modules

  load_env_file:
    description: 'Generate .env file from CircleCI environment variables'
    steps:
      - run:
          name: Generate .env for build/runtime
          command: |
            echo "Generating .env from CircleCI variables..."
            cat > .env \<< EOF
            NEXT_LOG_LEVEL=${NEXT_LOG_LEVEL:-info}
            SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
            NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}
            E2B_API_KEY=${E2B_API_KEY:-}
            NODE_ENV=production
            EOF
            echo ".env generated"

  setup_test_directories:
    description: 'Create test results directories'
    steps:
      - run:
          name: Create test directories
          command: |
            mkdir -p src/__test__/results
            mkdir -p src/__test__/screenshots
            mkdir -p src/__test__/videos

  notify_github_status:
    description: 'Update GitHub status check'
    parameters:
      status:
        type: enum
        enum: ['pending', 'success', 'failure']
      context:
        type: string
    steps:
      - run:
          name: Update GitHub status
          command: |
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{
                "state": "<< parameters.status >>",
                "target_url": "https://circleci.com/gh/aibexx/core/'$CIRCLE_BUILD_NUM'",
                "description": "CircleCI build << parameters.status >>",
                "context": "<< parameters.context >>"
              }' \
              "https://api.github.com/repos/aibexx/core/statuses/$CIRCLE_SHA1"
          when: always

# Define the jobs
jobs:
  # LambdaTest E2E Testing - Windows Chrome
  e2e_lambdatest_windows:
    docker:
      - image: cimg/node:20.19.0-browsers
    working_directory: ~/project
    environment:
      LT_BUILD_NAME: 'AIBEXX-E2E-Windows-${CIRCLE_BUILD_NUM}'
      LT_TEST_NAME: 'AIBEXX-Windows-Chrome-E2E-Tests'
    resource_class: medium
    parallelism: 1
    steps:
      - checkout
      - notify_github_status:
          status: pending
          context: 'ci/e2e-windows'

      # Install dependencies and setup
      - install_dependencies
      - load_env_file
      - setup_test_directories

      # Install LambdaTest CLI and build app
      - run:
          name: 'Setup LambdaTest and build application'
          command: |
            sudo npm install -g lambdatest-cypress-cli
            npm run build

            # Update LambdaTest config for Windows Chrome
            sed -i "s|\${LT_USERNAME}|${LT_USERNAME}|g" lambdatest-config.json
            sed -i "s|\${LT_ACCESS_KEY}|${LT_ACCESS_KEY}|g" lambdatest-config.json
            sed -i "s|\${LT_BUILD_NAME:-AIBEXX-E2E-Local}|AIBEXX-E2E-Windows-${CIRCLE_BUILD_NUM}|g" lambdatest-config.json
            sed -i "s|\${NEXT_PUBLIC_SUPABASE_URL}|${NEXT_PUBLIC_SUPABASE_URL}|g" lambdatest-config.json
            sed -i "s|\${NEXT_PUBLIC_SUPABASE_ANON_KEY}|${NEXT_PUBLIC_SUPABASE_ANON_KEY}|g" lambdatest-config.json
            sed -i "s|\${SUPABASE_SERVICE_ROLE_KEY}|${SUPABASE_SERVICE_ROLE_KEY}|g" lambdatest-config.json
            sed -i "s|\${E2B_API_KEY}|${E2B_API_KEY}|g" lambdatest-config.json
            sed -i "s|\${CYPRESS_TEST_EMAIL}|${CYPRESS_TEST_EMAIL:-cypress-test@example.com}|g" lambdatest-config.json
            sed -i "s|\${CYPRESS_TEST_PASSWORD}|${CYPRESS_TEST_PASSWORD:-CypressTest123!}|g" lambdatest-config.json

      - run:
          name: 'Start application server'
          command: npm start
          background: true

      - run:
          name: 'Wait for application to be ready'
          command: |
            echo "Waiting for application to start..."
            for i in {1..60}; do
              if curl -f http://localhost:3000 > /dev/null 2>&1; then
                echo "Application is ready!"
                exit 0
              else
                echo "Attempt $i: App not ready yet..."
                sleep 2
              fi
            done
            echo "ERROR: Application failed to start"
            exit 1

      # Run Cypress E2E tests on LambdaTest Windows Chrome
      - run:
          name: 'Run E2E Tests on LambdaTest Windows Chrome'
          no_output_timeout: 15m
          command: |
            echo "Starting LambdaTest Windows Chrome execution..."
            echo "Build: AIBEXX-E2E-Windows-${CIRCLE_BUILD_NUM}"

            set +e
            npx lambdatest-cypress run \
              --config-file="lambdatest-config.json" \
              --cy="--config-file cypress.config.ts --browser chrome" \
              2>&1 | tee "lambdatest-output.log"

            LAMBDATEST_EXIT_CODE=$?
            set -e

            echo "=== LAMBDATEST OUTPUT ==="
            cat lambdatest-output.log
            echo "=== END OUTPUT ==="
            echo "LambdaTest CLI exit code: $LAMBDATEST_EXIT_CODE"

            # Validation layers
            if grep -qi "could not execute cypress run command\|Some Error occured on Lambdatest Server\|tunnel.*error\|authentication.*failed" lambdatest-output.log; then
              echo "❌ CRITICAL ERROR: LambdaTest execution failed"
              exit 1
            fi

            if ! grep -qi "running\|spec\|test\|it(" lambdatest-output.log; then
              echo "❌ ERROR: No tests appear to have run"
              exit 1
            fi

            if [ $LAMBDATEST_EXIT_CODE -ne 0 ]; then
              echo "❌ FAILURE: LambdaTest CLI failed (exit code: $LAMBDATEST_EXIT_CODE)"
              exit 1
            fi

            if grep -qi "passing\|failing\|✓\|✗\|passed\|failed" lambdatest-output.log; then
              echo "✅ SUCCESS: Tests executed and completed"
            else
              echo "❌ WARNING: No clear test results found"
              exit 1
            fi

            echo "✅ Windows Chrome tests completed successfully"

      # Store test artifacts
      - store_test_results:
          path: src/__test__/results
          when: always
      - store_artifacts:
          path: src/__test__/results
          destination: e2e-test-results-windows
          when: always
      - store_artifacts:
          path: lambdatest-output.log
          destination: lambdatest-output-windows.log
          when: always

      # Notify GitHub status
      - notify_github_status:
          status: success
          context: 'ci/e2e-windows'
      - run:
          name: 'Notify GitHub of Windows E2E test failure'
          command: |
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{
                "state": "failure",
                "target_url": "https://circleci.com/gh/aibexx/core/'$CIRCLE_BUILD_NUM'",
                "description": "Windows E2E tests failed on LambdaTest",
                "context": "ci/e2e-windows"
              }' \
              "https://api.github.com/repos/aibexx/core/statuses/$CIRCLE_SHA1"
          when: on_fail

  # LambdaTest E2E Testing - WebKit Safari
  e2e_lambdatest_webkit:
    docker:
      - image: cimg/node:20.19.0-browsers
    working_directory: ~/project
    environment:
      LT_BUILD_NAME: 'AIBEXX-E2E-WebKit-${CIRCLE_BUILD_NUM}'
      LT_TEST_NAME: 'AIBEXX-WebKit-Safari-E2E-Tests'
    resource_class: medium
    parallelism: 1
    steps:
      - checkout
      - notify_github_status:
          status: pending
          context: 'ci/e2e-webkit'

      # Install dependencies and setup
      - install_dependencies
      - load_env_file
      - setup_test_directories

      # Install LambdaTest CLI and build app
      - run:
          name: 'Setup LambdaTest and build application'
          command: |
            sudo npm install -g lambdatest-cypress-cli
            npm run build

            # Update LambdaTest config for WebKit Safari
            cp lambdatest-config.json lambdatest-webkit-config.json
            sed -i 's/"browser": "Chrome"/"browser": "Safari"/g' lambdatest-webkit-config.json
            sed -i 's/"platform": "Windows 11"/"platform": "macOS Monterey"/g' lambdatest-webkit-config.json
            sed -i "s|\${LT_USERNAME}|${LT_USERNAME}|g" lambdatest-webkit-config.json
            sed -i "s|\${LT_ACCESS_KEY}|${LT_ACCESS_KEY}|g" lambdatest-webkit-config.json
            sed -i "s|\${LT_BUILD_NAME:-AIBEXX-E2E-Local}|AIBEXX-E2E-WebKit-${CIRCLE_BUILD_NUM}|g" lambdatest-webkit-config.json
            sed -i "s|\${NEXT_PUBLIC_SUPABASE_URL}|${NEXT_PUBLIC_SUPABASE_URL}|g" lambdatest-webkit-config.json
            sed -i "s|\${NEXT_PUBLIC_SUPABASE_ANON_KEY}|${NEXT_PUBLIC_SUPABASE_ANON_KEY}|g" lambdatest-webkit-config.json
            sed -i "s|\${SUPABASE_SERVICE_ROLE_KEY}|${SUPABASE_SERVICE_ROLE_KEY}|g" lambdatest-webkit-config.json
            sed -i "s|\${E2B_API_KEY}|${E2B_API_KEY}|g" lambdatest-webkit-config.json
            sed -i "s|\${CYPRESS_TEST_EMAIL}|${CYPRESS_TEST_EMAIL:-cypress-test@example.com}|g" lambdatest-webkit-config.json
            sed -i "s|\${CYPRESS_TEST_PASSWORD}|${CYPRESS_TEST_PASSWORD:-CypressTest123!}|g" lambdatest-webkit-config.json

      - run:
          name: 'Start application server'
          command: npm start
          background: true

      - run:
          name: 'Wait for application to be ready'
          command: |
            echo "Waiting for application to start..."
            for i in {1..60}; do
              if curl -f http://localhost:3000 > /dev/null 2>&1; then
                echo "Application is ready!"
                exit 0
              else
                echo "Attempt $i: App not ready yet..."
                sleep 2
              fi
            done
            echo "ERROR: Application failed to start"
            exit 1

      # Run Cypress E2E tests on LambdaTest WebKit Safari
      - run:
          name: 'Run E2E Tests on LambdaTest WebKit Safari'
          no_output_timeout: 15m
          command: |
            echo "Starting LambdaTest WebKit Safari execution..."
            echo "Build: AIBEXX-E2E-WebKit-${CIRCLE_BUILD_NUM}"

            set +e
            npx lambdatest-cypress run \
              --config-file="lambdatest-webkit-config.json" \
              --cy="--config-file cypress.config.ts --browser webkit" \
              2>&1 | tee "lambdatest-webkit-output.log"

            LAMBDATEST_EXIT_CODE=$?
            set -e

            echo "=== LAMBDATEST WEBKIT OUTPUT ==="
            cat lambdatest-webkit-output.log
            echo "=== END OUTPUT ==="
            echo "LambdaTest CLI exit code: $LAMBDATEST_EXIT_CODE"

            # Validation layers
            if grep -qi "could not execute cypress run command\|Some Error occured on Lambdatest Server\|tunnel.*error\|authentication.*failed" lambdatest-webkit-output.log; then
              echo "❌ CRITICAL ERROR: LambdaTest WebKit execution failed"
              exit 1
            fi

            if ! grep -qi "running\|spec\|test\|it(" lambdatest-webkit-output.log; then
              echo "❌ ERROR: No tests appear to have run"
              exit 1
            fi

            if [ $LAMBDATEST_EXIT_CODE -ne 0 ]; then
              echo "❌ FAILURE: LambdaTest CLI failed (exit code: $LAMBDATEST_EXIT_CODE)"
              exit 1
            fi

            if grep -qi "passing\|failing\|✓\|✗\|passed\|failed" lambdatest-webkit-output.log; then
              echo "✅ SUCCESS: Tests executed and completed"
            else
              echo "❌ WARNING: No clear test results found"
              exit 1
            fi

      # Store test artifacts
      - store_test_results:
          path: src/__test__/results
          when: always
      - store_artifacts:
          path: src/__test__/results
          destination: e2e-test-results-webkit
          when: always
      - store_artifacts:
          path: lambdatest-webkit-output.log
          destination: lambdatest-output-webkit.log
          when: always

      # Notify GitHub status
      - notify_github_status:
          status: success
          context: 'ci/e2e-webkit'
      - run:
          name: 'Notify GitHub of WebKit E2E test failure'
          command: |
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{
                "state": "failure",
                "target_url": "https://circleci.com/gh/aibexx/core/'$CIRCLE_BUILD_NUM'",
                "description": "WebKit E2E tests failed on LambdaTest",
                "context": "ci/e2e-webkit"
              }' \
              "https://api.github.com/repos/aibexx/core/statuses/$CIRCLE_SHA1"
          when: on_fail

workflows:
  e2e_cross_browser:
    jobs:
      - e2e_lambdatest_windows
      - e2e_lambdatest_webkit
